# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import command_pb2 as command__pb2


class CommandInterfaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Command = channel.unary_unary(
        '/grpc.CommandInterface/Command',
        request_serializer=command__pb2.CommandRequest.SerializeToString,
        response_deserializer=command__pb2.ErrorStatus.FromString,
        )
    self.GetHelp = channel.unary_unary(
        '/grpc.CommandInterface/GetHelp',
        request_serializer=command__pb2.CommandHelprequest.SerializeToString,
        response_deserializer=command__pb2.CommandHelpResp.FromString,
        )


class CommandInterfaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Command(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHelp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommandInterfaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Command': grpc.unary_unary_rpc_method_handler(
          servicer.Command,
          request_deserializer=command__pb2.CommandRequest.FromString,
          response_serializer=command__pb2.ErrorStatus.SerializeToString,
      ),
      'GetHelp': grpc.unary_unary_rpc_method_handler(
          servicer.GetHelp,
          request_deserializer=command__pb2.CommandHelprequest.FromString,
          response_serializer=command__pb2.CommandHelpResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc.CommandInterface', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
