workspace:
  base: /go
  path: src/github.com/zhsyourai/URCF-engine

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get
      - go test
      - go build

matrix:
 GO_VERSION:
   - latest
   - "1.8"