// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

/*
Package plugin_protocol is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	ErrorStatus
	CommandRequest
	CommandHelprequest
	CommandHelpResp
*/
package plugin_protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorStatus struct {
	Message string                 `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Details []*google_protobuf.Any `protobuf:"bytes,2,rep,name=details" json:"details,omitempty"`
}

func (m *ErrorStatus) Reset()                    { *m = ErrorStatus{} }
func (m *ErrorStatus) String() string            { return proto.CompactTextString(m) }
func (*ErrorStatus) ProtoMessage()               {}
func (*ErrorStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorStatus) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type CommandRequest struct {
	Name   string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Params []*google_protobuf.Any `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommandRequest) GetParams() []*google_protobuf.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

type CommandHelprequest struct {
	Subcommand string `protobuf:"bytes,1,opt,name=subcommand" json:"subcommand,omitempty"`
}

func (m *CommandHelprequest) Reset()                    { *m = CommandHelprequest{} }
func (m *CommandHelprequest) String() string            { return proto.CompactTextString(m) }
func (*CommandHelprequest) ProtoMessage()               {}
func (*CommandHelprequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommandHelprequest) GetSubcommand() string {
	if m != nil {
		return m.Subcommand
	}
	return ""
}

type CommandHelpResp struct {
	Help string `protobuf:"bytes,1,opt,name=help" json:"help,omitempty"`
}

func (m *CommandHelpResp) Reset()                    { *m = CommandHelpResp{} }
func (m *CommandHelpResp) String() string            { return proto.CompactTextString(m) }
func (*CommandHelpResp) ProtoMessage()               {}
func (*CommandHelpResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandHelpResp) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorStatus)(nil), "plugin.protocol.ErrorStatus")
	proto.RegisterType((*CommandRequest)(nil), "plugin.protocol.CommandRequest")
	proto.RegisterType((*CommandHelprequest)(nil), "plugin.protocol.CommandHelprequest")
	proto.RegisterType((*CommandHelpResp)(nil), "plugin.protocol.CommandHelpResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CommandInterface service

type CommandInterfaceClient interface {
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*ErrorStatus, error)
	GetHelp(ctx context.Context, in *CommandHelprequest, opts ...grpc.CallOption) (*CommandHelpResp, error)
}

type commandInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewCommandInterfaceClient(cc *grpc.ClientConn) CommandInterfaceClient {
	return &commandInterfaceClient{cc}
}

func (c *commandInterfaceClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*ErrorStatus, error) {
	out := new(ErrorStatus)
	err := grpc.Invoke(ctx, "/plugin.protocol.CommandInterface/Command", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandInterfaceClient) GetHelp(ctx context.Context, in *CommandHelprequest, opts ...grpc.CallOption) (*CommandHelpResp, error) {
	out := new(CommandHelpResp)
	err := grpc.Invoke(ctx, "/plugin.protocol.CommandInterface/GetHelp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommandInterface service

type CommandInterfaceServer interface {
	Command(context.Context, *CommandRequest) (*ErrorStatus, error)
	GetHelp(context.Context, *CommandHelprequest) (*CommandHelpResp, error)
}

func RegisterCommandInterfaceServer(s *grpc.Server, srv CommandInterfaceServer) {
	s.RegisterService(&_CommandInterface_serviceDesc, srv)
}

func _CommandInterface_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandInterfaceServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.protocol.CommandInterface/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandInterfaceServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandInterface_GetHelp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandHelprequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandInterfaceServer).GetHelp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.protocol.CommandInterface/GetHelp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandInterfaceServer).GetHelp(ctx, req.(*CommandHelprequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.protocol.CommandInterface",
	HandlerType: (*CommandInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _CommandInterface_Command_Handler,
		},
		{
			MethodName: "GetHelp",
			Handler:    _CommandInterface_GetHelp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command.proto",
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xe9, 0xff, 0x2f, 0x5b, 0x9c, 0x45, 0x57, 0x06, 0x0f, 0xb5, 0x88, 0x96, 0x8a, 0xb0,
	0x07, 0xc9, 0xc2, 0xea, 0x17, 0x10, 0x11, 0xd7, 0x9b, 0xd4, 0x83, 0xe7, 0xb4, 0x3b, 0x5b, 0x17,
	0xd2, 0x24, 0x26, 0xe9, 0x61, 0xbf, 0x94, 0x9f, 0x51, 0xda, 0x26, 0x50, 0x15, 0xf7, 0x96, 0x99,
	0x79, 0xf9, 0xf1, 0xde, 0x83, 0xa3, 0x4a, 0x35, 0x0d, 0x97, 0x6b, 0xa6, 0x8d, 0x72, 0x0a, 0x67,
	0x5a, 0xb4, 0xf5, 0x56, 0x0e, 0x53, 0xa5, 0x44, 0x7a, 0x56, 0x2b, 0x55, 0x0b, 0x5a, 0xf4, 0x8b,
	0xb2, 0xdd, 0x2c, 0xb8, 0xdc, 0x0d, 0xd7, 0xfc, 0x0d, 0xa6, 0x8f, 0xc6, 0x28, 0xf3, 0xea, 0xb8,
	0x6b, 0x2d, 0x26, 0x10, 0x37, 0x64, 0x2d, 0xaf, 0x29, 0x89, 0xb2, 0x68, 0x7e, 0x58, 0x84, 0x11,
	0x19, 0xc4, 0x6b, 0x72, 0x7c, 0x2b, 0x6c, 0xf2, 0x2f, 0xfb, 0x3f, 0x9f, 0x2e, 0x4f, 0xd9, 0x40,
	0x65, 0x81, 0xca, 0xee, 0xe5, 0xae, 0x08, 0xa2, 0xbc, 0x80, 0xe3, 0x87, 0xc1, 0x55, 0x41, 0x1f,
	0x2d, 0x59, 0x87, 0x08, 0x07, 0x92, 0x37, 0x01, 0xdc, 0xbf, 0xf1, 0x06, 0x26, 0x9a, 0x1b, 0xde,
	0xec, 0x87, 0x7a, 0x4d, 0x7e, 0x07, 0xe8, 0x99, 0x2b, 0x12, 0xda, 0x78, 0xee, 0x05, 0x80, 0x6d,
	0x4b, 0x5f, 0x81, 0xa7, 0x8f, 0x36, 0xf9, 0x35, 0xcc, 0x46, 0xbf, 0x0a, 0xb2, 0xba, 0xb3, 0xf2,
	0x4e, 0x42, 0x07, 0x2b, 0xdd, 0x7b, 0xf9, 0x19, 0xc1, 0x89, 0xd7, 0x3d, 0x4b, 0x47, 0x66, 0xc3,
	0x2b, 0xc2, 0x15, 0xc4, 0x7e, 0x87, 0x97, 0xec, 0x47, 0xad, 0xec, 0x7b, 0xbe, 0xf4, 0xfc, 0x97,
	0x60, 0xdc, 0xec, 0x0b, 0xc4, 0x4f, 0xe4, 0x3a, 0x07, 0x78, 0xf5, 0x17, 0x69, 0x94, 0x2a, 0xcd,
	0xf6, 0x89, 0xba, 0x10, 0xe5, 0xa4, 0xbf, 0xdc, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xa3,
	0xcb, 0xf0, 0xfe, 0x01, 0x00, 0x00,
}
